# Generated by Django 4.0.6 on 2022-07-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otziv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=35)),
                ('address', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=5000)),
            ],
        ),
    ]
