# Generated by Django 4.0.6 on 2022-07-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_otziv_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otziv',
            old_name='text',
            new_name='message',
        ),
    ]
